### ISSUE TITLE
来个国内镜像站呗

### ISSUE THREAD

**Issue by CoREse** [shidahuilang/shuyuan#20]
github半墙状态，而里面的小说源又是国内网站。如果把阅读上梯子吧，找源不方便，不上梯子吧，更新不了规则，很麻烦啊。（不要说什么梯子规则啦）
如果能有个国内镜像站就好啦！

**Comment by shidahuilang** [comment]
可以添加cdn，http://mirror.ghproxy.com/https://raw.githubusercontent.com/shidahuilang/shuyuan/shuyuan/book.json 比如这样，网址前面添加http://mirror.ghproxy.com/

**Comment by CoREse** [comment]
> 可以添加cdn，http://mirror.ghproxy.com/https://raw.githubusercontent.com/shidahuilang/shuyuan/shuyuan/book.json 比如这样，网址前面添加http://mirror.ghproxy.com/

哦哦！还可以这样！思路打开！学到了学到了！感谢！
