### ISSUE TITLE
书源找不到数据

### ISSUE THREAD

**Issue by silentpride** [shidahuilang/shuyuan#23]
用的这个链接
https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs

![image](https://github.com/shidahuilang/shuyuan/assets/21210520/55d8b0e7-b165-45c6-ab86-16477e41b04b)

**Comment by shidahuilang** [comment]
https://github.com/shidahuilang/shuyuan/raw/shuyuan/aiyueshuxiang.ibs

**Comment by 19143509266** [comment]
挂梯子
