### ISSUE TITLE
导入链接，提示错误的URL

### ISSUE THREAD

**Issue by YiFoneChen** [shidahuilang/shuyuan#26]
![IMG_6141](https://github.com/shidahuilang/shuyuan/assets/77783848/b2c8d443-5fd1-46c2-815b-75a7784d0b15)
![IMG_6140](https://github.com/shidahuilang/shuyuan/assets/77783848/84c98da8-1d6c-4ce1-800a-b7818243ab1d)
如图，香色闺阁2.56.1导入链接，提示错误的URL
请问是怎么回事

**Comment by shidahuilang** [comment]
翻墙网络

**Comment by shidahuilang** [comment]
我这边测试都没问题
