### ISSUE TITLE
tts 语音用不了，提示如下

### ISSUE THREAD

**Issue by WoChen5770** [shidahuilang/shuyuan#7]
Error 1101 Ray ID: 8325ea60dc942ac7 • 2023-12-08 15:07:00 UTC
Worker threw exception
What happened?
You've requested a page on a website (tts.dalang.eu.org) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. An unknown error occurred while rendering the page.

What can I do?
If you are the owner of this website:
you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and check the error logs for tts.dalang.eu.org.

**Comment by shidahuilang** [comment]
接口挂了

**Comment by WoChen5770** [comment]
> 接口挂了

还有其他好用的接口不

**Comment by shidahuilang** [comment]
有
