### ISSUE TITLE
爱阅书香

### ISSUE THREAD

**Issue by a185039136** [shidahuilang/shuyuan#8]
爱阅书香的书源地址是已经改了吗？同步更新反而啥都没有？

**Comment by shidahuilang** [comment]
没有改

**Comment by shidahuilang** [comment]
http://mirror.ghproxy.com/http://mirror.ghproxy.com/https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs

**Comment by a185039136** [comment]
> http://mirror.ghproxy.com/http://mirror.ghproxy.com/https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs
![微信图片_20231213155932](https://github.com/shidahuilang/shuyuan/assets/78145534/2e873aed-5182-410e-b0d6-ac1b278279d9)
是我操作有问题吗？怎么同步不了doge

**Comment by shidahuilang** [comment]
http://mirror.ghproxy.com/https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs   这样把加速cdn去掉

> > http://mirror.ghproxy.com/http://mirror.ghproxy.com/https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs
> > ![微信图片_20231213155932](https://private-user-images.githubusercontent.com/78145534/290116967-2e873aed-5182-410e-b0d6-ac1b278279d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTUxNDQsIm5iZiI6MTcwMjQ1NDg0NCwicGF0aCI6Ii83ODE0NTUzNC8yOTAxMTY5NjctMmU4NzNhZWQtNTE4Mi00MTBlLWIwZDYtYWMxYjI3ODI3OWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA4MDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMTEwMWYyZjZjNWYxYjhmNGUzOGEyN2VkODQ2ZGQzMjdmYWY0MTE1N2YxOTIzMTQ1MjkyYzQ1MDlhYzhjN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SK3zpfbJ8EPgRvlDSzuWbmM7wShKcdtKtP5vI53jnQ)
> > 是我操作有问题吗？怎么同步不了doge

**Comment by shidahuilang** [comment]
https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs   这样试试看

**Comment by shidahuilang** [comment]
不好意思，是我的锅，多复制了一个[http://mirror.ghproxy.com]

**Comment by dutumn** [comment]
失效了？

**Comment by 805328993** [comment]
![image](https://github.com/shidahuilang/shuyuan/assets/150040391/5acdc568-211b-453f-82bd-1944ca11fb4e)这个怎么解决

**Comment by Alangpet** [comment]
> https://github.com/shidahuilang/shuyuan/raw/main/aiyueshuxiang.ibs 这样试试看

也不行，开了代理也不行，把IBS文件下载到本地使用爱阅书香打开倒是可以
![1](https://github.com/shidahuilang/shuyuan/assets/167532539/2ed230f5-ab88-48f3-afa9-08f4eb202737)
![2](https://github.com/shidahuilang/shuyuan/assets/167532539/25bbdf48-5716-4788-a578-6e40a45fb9c5)

**Comment by shidahuilang** [comment]
https://github.com/shidahuilang/shuyuan/raw/shuyuan/aiyueshuxiang.ibs
